/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WhatsupLayoutImport } from './routes/whatsup/_layout'
import { Route as WhatsupLayoutGameingImport } from './routes/whatsup/_layout/gameing'

// Create Virtual Routes

const WhatsupImport = createFileRoute('/whatsup')()
const TestLazyImport = createFileRoute('/test')()
const ContextLazyImport = createFileRoute('/context')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WhatsupRoute = WhatsupImport.update({
  path: '/whatsup',
  getParentRoute: () => rootRoute,
} as any)

const TestLazyRoute = TestLazyImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/test.lazy').then((d) => d.Route))

const ContextLazyRoute = ContextLazyImport.update({
  path: '/context',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/context.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WhatsupLayoutRoute = WhatsupLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => WhatsupRoute,
} as any)

const WhatsupLayoutGameingRoute = WhatsupLayoutGameingImport.update({
  path: '/gameing',
  getParentRoute: () => WhatsupLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/context': {
      preLoaderRoute: typeof ContextLazyImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      preLoaderRoute: typeof TestLazyImport
      parentRoute: typeof rootRoute
    }
    '/whatsup': {
      preLoaderRoute: typeof WhatsupImport
      parentRoute: typeof rootRoute
    }
    '/whatsup/_layout': {
      preLoaderRoute: typeof WhatsupLayoutImport
      parentRoute: typeof WhatsupRoute
    }
    '/whatsup/_layout/gameing': {
      preLoaderRoute: typeof WhatsupLayoutGameingImport
      parentRoute: typeof WhatsupLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ContextLazyRoute,
  TestLazyRoute,
  WhatsupRoute.addChildren([
    WhatsupLayoutRoute.addChildren([WhatsupLayoutGameingRoute]),
  ]),
])

/* prettier-ignore-end */
